language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - ./example/manage.py test formfield
branches:
  only:
    - master